// GitHub Actions workflow generation for `hooversion init`. This file ports
// src/workflow.ts byte-for-byte: the "# Generated by Hooversion" marker, the
// pinned action SHAs, the exact YAML layout (including the double blank line
// before `env:` in release.yml), and the generated-workflow overwrite rule.
package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	hverrors "github.com/openhoo/hooversion/internal/errors"
)

const (
	defaultActionOwnerRepo  = "openhoo/hooversion"
	defaultBunVersion       = "1.3.14"
	defaultReleaseBranch    = "main"
	checkoutSha             = "d23441a48e516b6c34aea4fa41551a30e30af803"
	setupBunSha             = "0c5077e51419868618aeaa5fe8019c62421857d6"
	generatedWorkflowMarker = "# Generated by Hooversion"
)

// workflowOptions carries init's workflow flags; empty fields fall back to
// the defaults of renderGitHubWorkflows in src/workflow.ts. cliVersion is
// the binary version used to resolve the default hooversionVersion: unlike
// the TS source there is no adjacent package.json, so a "dev" build falls
// back to the TS getPackageVersion fallback of 0.1.0.
type workflowOptions struct {
	actionOwnerRepo   string
	actionRef         string
	hooversionVersion string
	force             bool
	cliVersion        string
}

type renderedWorkflows struct{ ci, release string }

// writeGitHubWorkflows refuses to clobber user-owned workflows, then writes
// ci.yml and release.yml under .github/workflows and returns their paths.
func writeGitHubWorkflows(cwd string, opts workflowOptions) ([]string, error) {
	workflowDir := filepath.Join(cwd, ".github", "workflows")
	ciPath := filepath.Join(workflowDir, "ci.yml")
	releasePath := filepath.Join(workflowDir, "release.yml")
	rendered := renderGitHubWorkflows(opts)
	pairs := []struct{ path, content string }{
		{ciPath, rendered.ci},
		{releasePath, rendered.release},
	}
	for _, pair := range pairs {
		current, err := os.ReadFile(pair.path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, err
		}
		if !opts.force || !isGeneratedWorkflow(string(current), pair.content) {
			return nil, hverrors.New(
				"Refusing to overwrite existing workflow %s; remove it or rerun init with --force for a Hooversion-generated workflow.",
				pair.path)
		}
	}

	if err := os.MkdirAll(workflowDir, 0o755); err != nil {
		return nil, err
	}
	for _, pair := range pairs {
		if err := os.WriteFile(pair.path, []byte(pair.content), 0o644); err != nil {
			return nil, err
		}
	}
	return []string{ciPath, releasePath}, nil
}

func renderGitHubWorkflows(opts workflowOptions) renderedWorkflows {
	hooversionVersion := opts.hooversionVersion
	if hooversionVersion == "" {
		hooversionVersion = resolveWorkflowVersion(opts.cliVersion)
	}
	actionOwnerRepo := opts.actionOwnerRepo
	if actionOwnerRepo == "" {
		actionOwnerRepo = defaultActionOwnerRepo
	}
	actionRef := opts.actionRef
	if actionRef == "" {
		actionRef = "v" + hooversionVersion
	}
	releaseBranch := defaultReleaseBranch

	body := fmt.Sprintf(`name: CI

on:
  pull_request:
  push:
    branches:
      - %[5]s

permissions:
  contents: read

env:
  HOOVERSION_VERSION: %[1]s

jobs:
  commitlint:
    name: Lint commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@%[3]s # v6
        with:
          fetch-depth: 0

      - name: Lint commits
        uses: %[6]s/actions/lint@%[7]s
        with:
          version: ${{ env.HOOVERSION_VERSION }}
          bun-version: %[2]s

  build:
    name: Test and build
    runs-on: ubuntu-latest
    needs: commitlint
    steps:
      - name: Checkout
        uses: actions/checkout@%[3]s # v6

      - name: Set up Bun
        uses: oven-sh/setup-bun@%[4]s # v2
        with:
          bun-version: %[2]s

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run checks
        run: bun run check
`, hooversionVersion, defaultBunVersion, checkoutSha, setupBunSha,
		releaseBranch, actionOwnerRepo, actionRef)

	ci := generatedWorkflowMarker + "\n" + body

	body = fmt.Sprintf(`name: Release

on:
  workflow_run:
    workflows:
      - CI
    branches:
      - %[5]s
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: release-${{ github.repository }}
  cancel-in-progress: false


env:
  HOOVERSION_VERSION: %[1]s

jobs:
  release:
    name: Release
    if: >-
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == '%[5]s' && !contains(github.event.workflow_run.head_commit.message, 'chore(release):')) ||
      (github.event_name == 'workflow_dispatch' && github.ref_name == '%[5]s')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@%[3]s # v6
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}

      - name: Release
        id: release
        uses: %[6]s/actions/release@%[7]s
        with:
          version: ${{ env.HOOVERSION_VERSION }}
          bun-version: %[2]s
          github-token: ${{ secrets.GITHUB_TOKEN }}
          install-command: bun install --frozen-lockfile
`, hooversionVersion, defaultBunVersion, checkoutSha, setupBunSha,
		releaseBranch, actionOwnerRepo, actionRef)

	release := generatedWorkflowMarker + "\n" + body

	return renderedWorkflows{ci: ci, release: release}
}

// isGeneratedWorkflow allows --force replacement when the existing file is a
// previous Hooversion-generated workflow or byte-identical to the new one.
func isGeneratedWorkflow(current, expected string) bool {
	return strings.HasPrefix(current, generatedWorkflowMarker+"\n") || current == expected
}

// resolveWorkflowVersion mirrors getPackageVersion's fallback: real versions
// flow through; dev builds use the TS package.json-missing fallback 0.1.0.
func resolveWorkflowVersion(cliVersion string) string {
	if cliVersion != "" && cliVersion != "dev" {
		return cliVersion
	}
	return "0.1.0"
}
