// GitHub Actions workflow generation for `hooversion init`.
package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	hverrors "github.com/openhoo/hooversion/internal/errors"
	"github.com/openhoo/hooversion/internal/semver"
	"github.com/openhoo/hooversion/internal/types"
)

const (
	defaultActionOwnerRepo  = "openhoo/hooversion"
	defaultActionVersion    = "1.1.0"
	defaultReleaseBranch    = "main"
	checkoutSha             = "3d3c42e5aac5ba805825da76410c181273ba90b1"
	setupBunSha             = "0c5077e51419868618aeaa5fe8019c62421857d6"
	setupNodeSha            = "820762786026740c76f36085b0efc47a31fe5020"
	generatedWorkflowMarker = "# Generated by Hooversion"
)

var (
	fullSHA            = regexp.MustCompile(`^[0-9a-fA-F]{40}$`)
	nodeVersionPattern = regexp.MustCompile(`^\d+(?:\.(?:\d+|[xX*])){0,2}$`)
	nodeRangeToken     = regexp.MustCompile(`^(>=|<=|>|<|=|~|\^)?v?(\d+(?:\.(?:\d+|[xX*])){0,2})$`)
)

// Known release commits are embedded so normal init runs do not need network
// access. The default action version is deliberately independent of the
// workflow's Hooversion CLI version: a new CLI can generate workflows that
// still consume the latest published action release.
var knownActionRefs = map[string]string{
	"1.1.0": "f2186561c587b58c5ea08c74c15800cdd39eab42",
}

type workflowProjectKind string

const (
	workflowBun         workflowProjectKind = "bun"
	workflowNode        workflowProjectKind = "node"
	workflowRust        workflowProjectKind = "rust"
	workflowVersionFile workflowProjectKind = "version-file"
)

type workflowProject struct {
	kind             workflowProjectKind
	workingDirectory string
	installCommand   string
	checkCommand     string
	bunVersion       string
	nodeVersion      string
}

// workflowOptions carries init's workflow flags and the detected project
// evidence used to select safe build and release commands.
type workflowOptions struct {
	actionOwnerRepo   string
	actionRef         string
	hooversionVersion string
	force             bool
	cliVersion        string
	packages          []types.PackageConfig
	project           workflowProject
}

type renderedWorkflows struct{ ci, release string }

// writeGitHubWorkflows refuses to clobber user-owned workflows, then writes
// ci.yml and release.yml under .github/workflows and returns their paths.
func writeGitHubWorkflows(cwd string, opts workflowOptions) ([]string, error) {
	if len(opts.packages) == 0 {
		return nil, hverrors.New("Could not infer a safe workflow because no package evidence was provided; rerun with --no-workflow and configure CI manually.")
	}
	project, err := inferWorkflowProject(cwd, opts.packages)
	if err != nil {
		return nil, err
	}
	opts.project = project
	rendered, err := renderGitHubWorkflows(opts)
	if err != nil {
		return nil, err
	}

	workflowDir := filepath.Join(cwd, ".github", "workflows")
	ciPath := filepath.Join(workflowDir, "ci.yml")
	releasePath := filepath.Join(workflowDir, "release.yml")
	pairs := []struct{ path, content string }{
		{ciPath, rendered.ci},
		{releasePath, rendered.release},
	}
	for _, pair := range pairs {
		current, err := os.ReadFile(pair.path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, err
		}
		if !opts.force || !isGeneratedWorkflow(string(current), pair.content) {
			return nil, hverrors.New(
				"Refusing to overwrite existing workflow %s; remove it or rerun init with --force for a Hooversion-generated workflow.",
				pair.path)
		}
	}

	if err := os.MkdirAll(workflowDir, 0o755); err != nil {
		return nil, err
	}
	for _, pair := range pairs {
		if err := os.WriteFile(pair.path, []byte(pair.content), 0o644); err != nil {
			return nil, err
		}
	}
	return []string{ciPath, releasePath}, nil
}

func inferWorkflowProject(cwd string, packages []types.PackageConfig) (workflowProject, error) {
	if len(packages) == 0 {
		return workflowProject{}, workflowInferenceError("no package evidence")
	}
	if len(packages) > 1 {
		return workflowProject{}, workflowInferenceError("the published immutable release action does not support multi-package workflows until it accepts releases-json")
	}
	kinds := make(map[types.PackageType]bool)
	for _, pkg := range packages {
		kinds[pkg.Type] = true
	}
	if kinds[types.PackagePython] {
		return workflowProject{}, workflowInferenceError("Python commands cannot be inferred safely")
	}
	if len(kinds) != 1 {
		return workflowProject{}, workflowInferenceError("mixed package ecosystems require explicit workflow commands")
	}

	switch packages[0].Type {
	case types.PackageNode:
		return inferNodeWorkflowProject(cwd, packages[0])
	case types.PackageRust:
		project := workflowProject{kind: workflowRust, checkCommand: "cargo test --workspace --all-targets --all-features"}
		if fileExists(filepath.Join(cwd, "Cargo.lock")) {
			project.checkCommand = "cargo test --locked --workspace --all-targets --all-features"
		}
		return project, nil
	case types.PackageVersionFile:
		return workflowProject{kind: workflowVersionFile}, nil
	default:
		return workflowProject{}, workflowInferenceError("unsupported package ecosystem")
	}
}

func workflowInferenceError(reason string) error {
	return hverrors.New("Cannot infer a safe GitHub workflow: %s. Rerun with --no-workflow and configure the ecosystem's checks manually.", reason)
}

type nodeManifest struct {
	PackageManager string `json:"packageManager"`
	Engines        struct {
		Node string `json:"node"`
	} `json:"engines"`
	Scripts map[string]json.RawMessage `json:"scripts"`
}

func inferNodeWorkflowProject(cwd string, pkg types.PackageConfig) (workflowProject, error) {
	root := filepath.Join(cwd, pkg.Path)
	manifestPath := filepath.Join(root, "package.json")
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return workflowProject{}, hverrors.New("Cannot infer a safe GitHub workflow: unable to read %s. Rerun with --no-workflow and configure the Node checks manually.", manifestPath)
	}
	var manifest nodeManifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return workflowProject{}, hverrors.New("Cannot infer a safe GitHub workflow: invalid %s. Rerun with --no-workflow and configure the Node checks manually.", manifestPath)
	}

	manager, managerVersion, err := parsePackageManager(manifest.PackageManager)
	if err != nil {
		return workflowProject{}, err
	}
	lockManager := ""
	for candidate, candidateManager := range map[string]string{
		"bun.lock":          "bun",
		"bun.lockb":         "bun",
		"package-lock.json": "npm",
	} {
		if !fileExists(filepath.Join(root, candidate)) {
			continue
		}
		if lockManager != "" && lockManager != candidateManager {
			return workflowProject{}, workflowInferenceError("conflicting Node lockfiles")
		}
		lockManager = candidateManager
	}
	if manager == "" {
		manager = lockManager
	} else if lockManager != "" && manager != lockManager {
		return workflowProject{}, workflowInferenceError("packageManager conflicts with the detected lockfile")
	}
	if manager == "" {
		return workflowProject{}, workflowInferenceError("Node package manager evidence is missing")
	}

	checkCommand := ""
	if _, ok := manifest.Scripts["check"]; ok {
		checkCommand = manager + " run check"
	} else if _, ok := manifest.Scripts["test"]; ok {
		checkCommand = manager + " run test"
	}
	project := workflowProject{kind: workflowNode, workingDirectory: workflowWorkingDirectory(pkg.Path), checkCommand: checkCommand}
	switch manager {
	case "bun":
		if managerVersion == "" {
			return workflowProject{}, workflowInferenceError("Bun packageManager must include an exact version")
		}
		project.kind = workflowBun
		project.bunVersion = managerVersion
		project.installCommand = "bun install"
		if lockManager == "bun" {
			project.installCommand = "bun install --frozen-lockfile"
		}
	case "npm":
		project.nodeVersion, err = inferNodeVersion(root, manifest.Engines.Node)
		if err != nil {
			return workflowProject{}, err
		}
		project.installCommand = "npm install"
		if lockManager == "npm" {
			project.installCommand = "npm ci"
		}
	}
	return project, nil
}

func workflowWorkingDirectory(raw string) string {
	if raw == "" {
		return "."
	}
	return filepath.ToSlash(filepath.Clean(raw))
}

// yamlScalar uses JSON string quoting, which is a valid YAML double-quoted
// scalar and preserves paths containing YAML punctuation or line breaks.
func yamlScalar(value string) string {
	encoded, _ := json.Marshal(value)
	return string(encoded)
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

func releaseInstallCommand(project workflowProject) string {
	if project.installCommand == "" || project.workingDirectory == "" || project.workingDirectory == "." {
		return project.installCommand
	}
	return "cd -- " + shellQuote(project.workingDirectory) + " && " + project.installCommand
}

func pathWorkingDirectory(project workflowProject) string {
	if project.workingDirectory == "" || project.workingDirectory == "." {
		return ""
	}
	return yamlScalar(project.workingDirectory)
}

func parsePackageManager(raw string) (string, string, error) {
	value := strings.TrimSpace(raw)
	if value == "" {
		return "", "", nil
	}
	manager, version := value, ""
	hasVersionSeparator := false
	if index := strings.IndexByte(value, '@'); index >= 0 {
		hasVersionSeparator = true
		manager, version = strings.TrimSpace(value[:index]), strings.TrimSpace(value[index+1:])
	}
	if manager != "bun" && manager != "npm" {
		return "", "", workflowInferenceError("unsupported Node package manager " + manager)
	}
	if version == "" {
		if hasVersionSeparator {
			return "", "", workflowInferenceError("invalid packageManager version")
		}
		return manager, "", nil
	}
	parsed, err := semver.Parse(version)
	if err != nil {
		return "", "", workflowInferenceError("invalid packageManager version " + version)
	}
	return manager, parsed.String(), nil
}

func inferNodeVersion(root, declared string) (string, error) {
	var candidates []string
	add := func(raw, source string) error {
		version, err := normalizeNodeVersion(raw)
		if err != nil {
			return workflowInferenceError("invalid Node runtime evidence in " + source)
		}
		candidates = append(candidates, version)
		return nil
	}
	if strings.TrimSpace(declared) != "" {
		if err := add(declared, "package.json engines.node"); err != nil {
			return "", err
		}
	}
	for _, name := range []string{".nvmrc", ".node-version"} {
		data, err := os.ReadFile(filepath.Join(root, name))
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return "", err
		}
		if err := add(string(data), name); err != nil {
			return "", err
		}
	}
	if data, err := os.ReadFile(filepath.Join(root, ".tool-versions")); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			fields := strings.Fields(line)
			if len(fields) >= 2 && fields[0] == "nodejs" {
				if err := add(fields[1], ".tool-versions"); err != nil {
					return "", err
				}
			}
		}
	} else if !os.IsNotExist(err) {
		return "", err
	}
	if len(candidates) == 0 {
		return "", workflowInferenceError("Node runtime version evidence is missing")
	}
	for _, candidate := range candidates[1:] {
		if candidate != candidates[0] {
			return "", workflowInferenceError("Node runtime version evidence is ambiguous")
		}
	}
	return candidates[0], nil
}

func normalizeNodeVersion(raw string) (string, error) {
	value := strings.TrimSpace(raw)
	if value == "" || strings.ContainsAny(value, "\r\n") || strings.Contains(value, "||") {
		return "", fmt.Errorf("invalid Node version")
	}
	if version, err := semver.Parse(strings.TrimPrefix(value, "v")); err == nil {
		return version.String(), nil
	}
	if nodeVersionPattern.MatchString(value) {
		return strings.TrimSuffix(strings.TrimSuffix(strings.TrimSuffix(value, ".x"), ".X"), ".*"), nil
	}
	tokens := strings.Fields(value)
	lower, upper := "", ""
	upperExclusive := false
	for _, token := range tokens {
		match := nodeRangeToken.FindStringSubmatch(token)
		if match == nil {
			return "", fmt.Errorf("invalid Node version")
		}
		op, base := match[1], match[2]
		if op == "" {
			return "", fmt.Errorf("invalid Node version")
		}
		switch op {
		case ">", "^", "~", ">=", "=":
			if op == ">" {
				return "", fmt.Errorf("ambiguous Node version")
			}
			if lower != "" {
				return "", fmt.Errorf("ambiguous Node version")
			}
			lower = base
		case "<", "<=":
			if upper != "" {
				return "", fmt.Errorf("ambiguous Node version")
			}
			upper, upperExclusive = base, op == "<"
		}
	}
	if lower == "" {
		return "", fmt.Errorf("invalid Node version")
	}
	if upper != "" {
		lowerVersion, err := nodeVersionComparable(lower)
		if err != nil {
			return "", err
		}
		upperVersion, err := nodeVersionComparable(upper)
		if err != nil {
			return "", err
		}
		if lowerVersion.Major > upperVersion.Major ||
			(lowerVersion.Major == upperVersion.Major && lowerVersion.Minor > upperVersion.Minor) ||
			(lowerVersion.Major == upperVersion.Major && lowerVersion.Minor == upperVersion.Minor && lowerVersion.Patch > upperVersion.Patch) ||
			(upperExclusive && lowerVersion == upperVersion) {
			return "", fmt.Errorf("contradictory Node version range")
		}
		if lowerVersion.Major == upperVersion.Major {
			return lowerVersion.String(), nil
		}
	}
	return normalizeNodeVersion(lower)
}

func nodeVersionComparable(raw string) (semver.SemVer, error) {
	base := strings.TrimSuffix(strings.TrimSuffix(raw, ".x"), ".X")
	base = strings.TrimSuffix(base, ".*")
	parts := strings.Split(base, ".")
	for len(parts) < 3 {
		parts = append(parts, "0")
	}
	return semver.Parse(strings.Join(parts, "."))
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func renderGitHubWorkflows(opts workflowOptions) (renderedWorkflows, error) {
	hooversionVersion, err := resolveWorkflowVersion(opts.hooversionVersion, opts.cliVersion)
	if err != nil {
		return renderedWorkflows{}, err
	}
	actionOwnerRepo := opts.actionOwnerRepo
	if actionOwnerRepo == "" {
		actionOwnerRepo = defaultActionOwnerRepo
	}
	actionRef, err := resolveActionReference("", actionOwnerRepo, defaultActionVersion, opts.actionRef)
	if err != nil {
		return renderedWorkflows{}, err
	}
	project := opts.project
	if project.kind == "" {
		return renderedWorkflows{}, workflowInferenceError("detected package kind was not carried into rendering")
	}
	switch project.kind {
	case workflowBun:
		if project.bunVersion == "" {
			return renderedWorkflows{}, workflowInferenceError("Bun runtime version evidence is missing")
		}
	case workflowNode:
		if project.nodeVersion == "" {
			return renderedWorkflows{}, workflowInferenceError("Node runtime version evidence is missing")
		}
	}
	releaseBranch := defaultReleaseBranch

	var ci strings.Builder
	ci.WriteString(generatedWorkflowMarker + "\n")
	fmt.Fprintf(&ci, `name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - %s

permissions:
  contents: read

env:
  HOOVERSION_VERSION: %s

jobs:
  commitlint:
    name: Lint commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@%s # v7
        with:
          fetch-depth: 0

      - name: Lint commits
        uses: %s/actions/lint@%s # v%s
        with:
          version: ${{ env.HOOVERSION_VERSION }}
  build:
    name: Test and build
    runs-on: ubuntu-latest
    needs: commitlint
    steps:
      - name: Checkout
        uses: actions/checkout@%s # v7
`, releaseBranch, hooversionVersion, checkoutSha, actionOwnerRepo, actionRef, defaultActionVersion, checkoutSha)
	writeBuildSteps(&ci, project)
	ci.WriteString("\n")

	var release strings.Builder
	release.WriteString(generatedWorkflowMarker + "\n")
	fmt.Fprintf(&release, `name: Release

on:
  workflow_run:
    workflows:
      - CI
    branches:
      - %s
    types:
      - completed
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: release-${{ github.repository }}
  cancel-in-progress: false

env:
  HOOVERSION_VERSION: %s

jobs:
  release:
    name: Release
    if: >-
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == '%s' && github.event.workflow_run.repository.full_name == github.repository) ||
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/%s')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      published: ${{ steps.finalize.outputs.published }}
      version: ${{ steps.finalize.outputs.version }}
      tag: ${{ steps.finalize.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@%s # v7
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}
`, releaseBranch, hooversionVersion, releaseBranch, releaseBranch, checkoutSha)
	if project.kind == workflowNode {
		writeRuntimeSetup(&release, project)
	}
	fmt.Fprintf(&release, `
      - name: Prepare protected-branch release
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && !startsWith(github.event.workflow_run.head_commit.message, 'chore(release):'))
        uses: %s/actions/prepare-release@%s # v%s
        with:
          version: ${{ env.HOOVERSION_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
`, actionOwnerRepo, actionRef, defaultActionVersion)
	if project.installCommand != "" {
		installCommand := releaseInstallCommand(project)
		if project.workingDirectory != "" && project.workingDirectory != "." {
			installCommand = yamlScalar(installCommand)
		}
		fmt.Fprintf(&release, "          install-command: %s\n", installCommand)
	}
	fmt.Fprintf(&release, `
      - name: Finalize protected-branch release
        id: finalize
        if: github.event_name == 'workflow_run' && startsWith(github.event.workflow_run.head_commit.message, 'chore(release):')
        uses: %s/actions/release@%s # v%s
        with:
          version: ${{ env.HOOVERSION_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
`, actionOwnerRepo, actionRef, defaultActionVersion)
	if project.installCommand != "" {
		installCommand := releaseInstallCommand(project)
		if project.workingDirectory != "" && project.workingDirectory != "." {
			installCommand = yamlScalar(installCommand)
		}
		fmt.Fprintf(&release, "          install-command: %s\n", installCommand)
	}

	return renderedWorkflows{ci: ci.String(), release: release.String()}, nil
}
func writeRuntimeSetup(b *strings.Builder, project workflowProject) {
	switch project.kind {
	case workflowBun:
		fmt.Fprintf(b, `
      - name: Set up Bun
        uses: oven-sh/setup-bun@%s # v2
        with:
          bun-version: %s
`, setupBunSha, project.bunVersion)
	case workflowNode:
		fmt.Fprintf(b, `
      - name: Set up Node
        uses: actions/setup-node@%s # v7
        with:
          node-version: %s
`, setupNodeSha, project.nodeVersion)
	case workflowRust:
		// The hosted runner includes Cargo; the check below remains lock-aware.
	}
}

func writeBuildSteps(b *strings.Builder, project workflowProject) {
	writeRuntimeSetup(b, project)
	if project.installCommand != "" {
		fmt.Fprintf(b, `
      - name: Install dependencies
`)
		if workingDirectory := pathWorkingDirectory(project); workingDirectory != "" {
			fmt.Fprintf(b, "        working-directory: %s\n", workingDirectory)
		}
		fmt.Fprintf(b, "        run: %s\n", project.installCommand)
	}
	if project.checkCommand != "" {
		fmt.Fprintf(b, `
      - name: Run checks
`)
		if workingDirectory := pathWorkingDirectory(project); workingDirectory != "" {
			fmt.Fprintf(b, "        working-directory: %s\n", workingDirectory)
		}
		fmt.Fprintf(b, "        run: %s\n", project.checkCommand)
	}
}

func resolveWorkflowVersion(explicit, cliVersion string) (string, error) {
	candidate := explicit
	if candidate == "" {
		candidate = cliVersion
	}
	if candidate == "" || candidate == "dev" {
		return "", hverrors.New("Unable to determine a Hooversion release version for generated workflows; provide --hooversion-version <version> or rerun with --no-workflow.")
	}
	candidate = strings.TrimSpace(candidate)
	candidate = strings.TrimPrefix(candidate, "v")
	parsed, err := semver.Parse(candidate)
	if err != nil {
		return "", hverrors.New("Invalid Hooversion release version %q; provide --hooversion-version <version> or rerun with --no-workflow.", candidate)
	}
	return parsed.String(), nil
}

func resolveActionReference(_ string, ownerRepo, version, explicit string) (string, error) {
	if explicit != "" {
		if !fullSHA.MatchString(explicit) {
			return "", hverrors.New("Invalid --action-ref %q: provide the full 40-character commit SHA, not a mutable tag.", explicit)
		}
		return strings.ToLower(explicit), nil
	}
	if ownerRepo == defaultActionOwnerRepo {
		if ref, ok := knownActionRefs[version]; ok {
			return ref, nil
		}
	}
	return "", hverrors.New("Unable to resolve the immutable Hooversion action commit for %s@v%s; provide --action-ref <full-40-character-commit-sha> (or rerun with --no-workflow).", ownerRepo, version)
}

// isGeneratedWorkflow allows --force replacement when the existing file is a
// previous Hooversion-generated workflow or byte-identical to the new one.
func isGeneratedWorkflow(current, expected string) bool {
	return strings.HasPrefix(current, generatedWorkflowMarker+"\n") || current == expected
}
