import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { HooversionError } from "./errors";

export interface GitHubWorkflowOptions {
  actionOwnerRepo?: string;
  actionRef?: string;
  hooversionVersion?: string;
  bunVersion?: string;
  releaseBranch?: string;
  force?: boolean;
}

const defaultActionOwnerRepo = "openhoo/hooversion";
const defaultBunVersion = "1.3.14";
const defaultReleaseBranch = "main";
const checkoutSha = "d23441a48e516b6c34aea4fa41551a30e30af803";
const generatedWorkflowMarker = "# Generated by Hooversion";
const setupBunSha = "0c5077e51419868618aeaa5fe8019c62421857d6";

export function writeGitHubWorkflow(cwd: string, options: GitHubWorkflowOptions = {}): string {
  return writeGitHubWorkflows(cwd, options)[0];
}

export function writeGitHubWorkflows(cwd: string, options: GitHubWorkflowOptions = {}): string[] {
  const workflowDir = join(cwd, ".github", "workflows");
  const ciPath = join(workflowDir, "ci.yml");
  const releasePath = join(workflowDir, "release.yml");
  const workflows = renderGitHubWorkflows(options);
  for (const [path, content] of [
    [ciPath, workflows.ci],
    [releasePath, workflows.release],
  ] as const) {
    if (existsSync(path) && (!options.force || !isGeneratedWorkflow(path, content))) {
      throw new HooversionError(
        `Refusing to overwrite existing workflow ${path}; remove it or rerun init with --force for a Hooversion-generated workflow.`,
      );
    }
  }

  mkdirSync(workflowDir, { recursive: true });
  writeFileSync(ciPath, workflows.ci);
  writeFileSync(releasePath, workflows.release);
  return [ciPath, releasePath];
}

export function renderGitHubWorkflow(options: GitHubWorkflowOptions = {}): string {
  return renderGitHubWorkflows(options).ci;
}

export function renderGitHubWorkflows(options: GitHubWorkflowOptions = {}): { ci: string; release: string } {
  const hooversionVersion = options.hooversionVersion ?? getPackageVersion();
  const actionOwnerRepo = options.actionOwnerRepo ?? defaultActionOwnerRepo;
  const actionRef = options.actionRef ?? `v${hooversionVersion}`;
  const bunVersion = options.bunVersion ?? defaultBunVersion;
  const releaseBranch = options.releaseBranch ?? defaultReleaseBranch;
  const ci = `${generatedWorkflowMarker}
name: CI

on:
  pull_request:
  push:
    branches:
      - ${releaseBranch}

permissions:
  contents: read

env:
  HOOVERSION_VERSION: ${hooversionVersion}

jobs:
  commitlint:
    name: Lint commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@${checkoutSha} # v6
        with:
          fetch-depth: 0

      - name: Lint commits
        uses: ${actionOwnerRepo}/actions/lint@${actionRef}
        with:
          version: \${{ env.HOOVERSION_VERSION }}
          bun-version: ${bunVersion}

  build:
    name: Test and build
    runs-on: ubuntu-latest
    needs: commitlint
    steps:
      - name: Checkout
        uses: actions/checkout@${checkoutSha} # v6

      - name: Set up Bun
        uses: oven-sh/setup-bun@${setupBunSha} # v2
        with:
          bun-version: ${bunVersion}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run checks
        run: bun run check
`;

  const release = `${generatedWorkflowMarker}
name: Release

on:
  workflow_run:
    workflows:
      - CI
    branches:
      - ${releaseBranch}
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: release-\${{ github.repository }}
  cancel-in-progress: false


env:
  HOOVERSION_VERSION: ${hooversionVersion}

jobs:
  release:
    name: Release
    if: >-
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == '${releaseBranch}' && !contains(github.event.workflow_run.head_commit.message, 'chore(release):')) ||
      (github.event_name == 'workflow_dispatch' && github.ref_name == '${releaseBranch}')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@${checkoutSha} # v6
        with:
          fetch-depth: 0
          ref: \${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}

      - name: Release
        id: release
        uses: ${actionOwnerRepo}/actions/release@${actionRef}
        with:
          version: \${{ env.HOOVERSION_VERSION }}
          bun-version: ${bunVersion}
          github-token: \${{ secrets.GITHUB_TOKEN }}
          install-command: bun install --frozen-lockfile
`;


  return { ci, release };
}

function isGeneratedWorkflow(path: string, expected: string): boolean {
  try {
    const current = readFileSync(path, "utf8");
    return current.startsWith(`${generatedWorkflowMarker}\n`) || current === expected;
  } catch {
    return false;
  }
}

function getPackageVersion(): string {
  const packagePath = new URL("../package.json", import.meta.url);
  if (!existsSync(packagePath)) return "0.1.0";
  const json = JSON.parse(readFileSync(packagePath, "utf8")) as { version?: string };
  return json.version ?? "0.1.0";
}
